apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: x9
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: x9
  template:
    metadata:
      labels:
        app: x9
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: x9
          image: x9:latest
          imagePullPolicy: IfNotPresent
          command: ["/app/bin/x9"]
          args: ["/var/log/x9/events.json", "/app/bin/x9.bpf.o"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: events
              mountPath: /var/log/x9
            - name: cgroup
              mountPath: /host/sys/fs/cgroup
              readOnly: true
            - name: pod-logs
              mountPath: /host/var/log/pods
              readOnly: true
      volumes:
        - name: events
          hostPath:
            path: /var/log/x9
            type: DirectoryOrCreate
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
            type: Directory
        - name: pod-logs
          hostPath:
            path: /var/log/pods
            type: DirectoryOrCreate
